---

- name: Build Maven project in the Docker Slave machine
  hosts: all
  #vars:
     #JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
     #M2_HOME: /usr/share/maven
     #PATH: $JAVA_HOME/bin:$M2_HOME/bin:$PATH
  #become: yes

  tasks:
    - name: Build Maven project
      shell: "mvn clean package"
      args: 
         chdir: /root/hello
      #env: "{{ environment }}"

    #- name: Install Maven software
      #apt: name=maven state=latest update_cache=yes

    #- debug: msg="Jenkins Docker Slave machine is configured successfully!"
